[package]
name = "blockchain"
version = "0.1.0"
authors = ["levi"]

[dependencies]
sha2 = "*"
vm = { path = "core/src/vm" }
blocks = { path = "blocks" }
transactions = { path = "core/src/transactions" }

[workspace]
members = [
	"core",
	"blocks",
	"rustcoin"
]

[[bin]]
path = "rustcoin/main.rs"
name = "rustcoind"
