[package]
name = "blockchain"
version = "0.1.0"
authors = ["levi"]

[dependencies]
sha2 = "*"
vm = { path = "src/core/src/vm" }
blocks = { path = "src/blocks" }
transactions = { path = "src/core/src/transactions" }