[package]
name = "wallet"
version = "0.1.0"
authors = ["Tancredi <dylanphoon@gmail.com>"]

[dependencies]
utils = {path = "../utils"}
consensus = {path = "../consensus"}

[lib]
name = "wallet"
path = "lib.rs"
