[package]
name = "blocks"
version = "0.1.0"
authors = ["Tancredi <dylanphoon@gmail.com>"]

[dependencies]
transactions = {path = "../core/transactions"}
vm = {path = "../core/rvm"}

[lib]
name = "blocks"
path = "lib.rs"
