[package]
name = "utils"
version = "0.1.0"
authors = ["Tancredi <dylanphoon@gmail.com>"]

[dependencies]
blocks = {path = "../blocks"}
chain = {path = "../chain"}
sha2 = "*"

[lib]
name = "utils"
path = "lib.rs"
