[package]
name = "consensus"
version = "0.1.0"
authors = ["Tancredi <dylanphoon@gmail.com>"]

[dependencies]
vm = {path = "../core/rvm"}
blocks = {path = "../blocks"}
utils = {path = "../utils"}
rkv = "*"

[lib]
path = "lib.rs"
name = "consensus"