[package]
name = "consensus"
version = "0.1.0"
authors = ["Tancredi <dylanphoon@gmail.com>"]

[dependencies]
vm = {path = "../core/rvm"}
blocks = {path = "../blocks"}
utils = {path = "../utils"}
db = {path = "../db"}
rkv = "*"
sha2 = "*"

[lib]
path = "lib.rs"
name = "consensus"